### PR TITLE
Wrap lines in output

### PR DESCRIPTION
**Pull request by nntrn**
Wrap lines in output (only noticable for json)

Screenshot 2023-08-05 at 9 33 01 PM

### CODE REVIEW

**Comment by jgm** [comment]
Thanks for this. But there are a lot of changes here, and it's hard to see what does what. For example, it looks like rules for .container are simply dropped.  12pt turns into 12px.  Etcetera.  Could you create a minimal PR that makes the least changes needed, adding other things in separate changes?  Or explain more fully the rationale for all of these changes?

**Comment by nntrn** [comment]
Updated to include the change I care about the most! I can add back the other changes later but would really love the word wrap (now or soonish) since I'm on trypandoc from my phone a lot

**Comment by jgm** [comment]
I'm hesitant about this, because pre-wrap can make it harder to see the difference caused by the wrap settings.  But let's try it.

**Comment by jgm** [comment]
Actually I have a better idea. I'll revert the pre-wrap. We can add special processing for JSON to format the JSON output using JS functions.

**Comment by jgm** [comment]
Implemented via commit 8fa927765fbc93dfacc302634aa52469e9d246b7

**Comment by nntrn** [comment]
YES!!! your fix is way better

**Pull request merged**
